### ISSUE TITLE
compute utf16 literal in const context

### ISSUE THREAD

**Issue by Lokathor** [rust-tutorials/triangle-from-scratch#12]

**Comment by thomcc** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d4bf36ff8d49186c4a299a81e67c1d01

Written a while ago for some apple code, but should be usable. It has some low hanging (compile-time) optimization fruit, but maybe i'll do that some other time.

**Comment by Lokathor** [comment]
ah excellent!

there's also this, which was PR'd to the utf16_lit crate, but that PR hasn't yet been published: https://github.com/Lokathor/utf16_lit/blob/main/src/lib.rs

I just need to take some time to do a write up of it all.
