### ISSUE TITLE
Full quantified names for constants

### ISSUE THREAD

**Issue by Mathspy** [rust-tutorials/triangle-from-scratch#22]
It’d be nice to mention the full quantified name for C constants when they’re mentioned for the first time, i.e `CS_OWNDC` is `Class Style OWNed Device Context`

**Comment by Lokathor** [comment]
So what I did instead is I added a comment on the front of the tutorial that you need to *actually* to read all the docs i link to all the time <3

**Comment by Mathspy** [comment]
Fair but they still didn't mention the full quantified names you had to basically stitch them together

**Comment by Lokathor** [comment]
Well on the [Window Class Styles](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-class-styles) page ("CS"), next to `CS_OWNDC` is says "Allocates a unique device context for each window in the class." ("OWN DC").

But I'll make that note in the tutorial.

**Comment by Mathspy** [comment]
Thanks c:
